# 端口号
server:
  port: 3035
# 应用名称
spring:
  application:
    name: redis-cache
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 数据库读取日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

# 配置mybatis-plus
mybatis-plus:
  type-aliases-package: com.vinjcent.pojo
  mapper-locations: classpath:com/vinjcent/mapper/**/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 开启日志监控
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      vinjcent:
        mapper: debug